import { Metadata } from "next";
import Link from "next/link";
import Breadcrumb from "@/components/Breadcrumb";
export const metadata: Metadata = { title: "Wer braucht eine UK ETA? Staatsangehörigkeit & Ausnahmen 2026", description: "Wer braucht eine UK ETA und wer ist befreit: britische und irische Staatsbürger, Personen mit Aufenthaltstitel, Airside-Transit. Leitfaden nach Nationalität." };
export default function Page() {
  return (<div>
      <section className="sub-hero relative overflow-hidden">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/sub-hero/what-is-eta.jpg" alt="" className="absolute inset-0 w-full h-full object-cover" />
        <div className="absolute inset-0 sub-hero-scrim" />
        <div className="relative max-w-4xl mx-auto px-6 pt-12 pb-12 md:pt-14 md:pb-16">
          <p className="kicker mb-3 mt-4">UK ETA INFORMATIONEN</p>
          <h1 className="deco-head text-3xl md:text-4xl font-bold text-white mb-6" style={{ fontFamily: "var(--font-noto-serif), serif" }}><span className="deco-line" />Wer braucht eine UK ETA?</h1>
          <p className="text-white/90 leading-relaxed" dangerouslySetInnerHTML={{__html:`Die UK ETA ist für Staatsangehörige visumfreier Länder bei Kurzaufenthalten erforderlich (Tourismus, Geschäft, Kurzstudium). <strong>Jeder Reisende, auch Babys und Kinder, benötigt eine eigene ETA.</strong>`}} />
        </div></section>
      <section className="bg-gray-50"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Wer ist von der ETA befreit</h2><ul className="space-y-3 text-gray-700 leading-relaxed"><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Britische und irische Staatsbürger (mit britischem/irischem Pass)`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Personen mit einer Erlaubnis zum Leben, Arbeiten oder Studieren im UK (z. B. Visum, Settled/Pre-settled Status)`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Inhaber eines British Overseas Territories Citizen- oder British National (Overseas)-Passes`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`In Irland Ansässige, die aus Irland, Guernsey, Jersey oder der Isle of Man reisen`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Airside-Transitreisende, die die Grenzkontrolle nicht passieren`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Personen, die auf das Ergebnis eines EU Settlement Scheme-Antrags warten`}} /></li></ul></div></section>
      <section className="bg-gray-50"><div className="max-w-4xl mx-auto px-6 py-10"><h2 className="heading-band mb-6">Wichtige Hinweise</h2><ul className="space-y-3 text-gray-700 leading-relaxed"><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Personen mit britischer oder irischer Staatsbürgerschaft können keine ETA erhalten und reisen mit den Dokumenten dieser Staatsbürgerschaft.`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Wenn Ihre Nationalität nicht visumbefreit ist, benötigen Sie möglicherweise ein Visum: Prüfen Sie dies mit dem offiziellen GOV.UK-Checker.`}} /></li><li className="flex gap-2"><span className="text-[#022444] font-bold">•</span><span dangerouslySetInnerHTML={{__html:`Auch Babys und Kinder benötigen eine eigene ETA.`}} /></li></ul></div></section>
      <section className="bg-white"><div className="max-w-4xl mx-auto px-6 py-8 text-sm text-gray-500"><p className="mb-2 font-bold text-gray-700">Offizielle Quellen (GOV.UK)</p><ul className="space-y-1"><li><a href="https://www.gov.uk/eta/when-not-need-eta" target="_blank" rel="noopener noreferrer" className="text-[#022444] underline">https://www.gov.uk/eta/when-not-need-eta</a></li><li><a href="https://www.gov.uk/guidance/check-when-you-can-get-an-electronic-travel-authorisation-eta" target="_blank" rel="noopener noreferrer" className="text-[#022444] underline">https://www.gov.uk/guidance/check-when-you-can-get-an-electronic-travel-authorisation-eta</a></li></ul></div></section>
      <div className="max-w-4xl mx-auto px-6 py-8"><Breadcrumb items={[{ label: "Startseite", href: "/" }, { label: "UK ETA Informationen", href: "/eta-info/what-is-eta" }, { label: "Wer braucht eine UK ETA?" }]} /></div>
    </div>);
}
